"""Init file for models."""
from . import bp_it_consumable_category
from . import bp_it_consumable_consumable
from . import bp_it_consumable_issue
from . import bp_it_consumable_request
from . import bp_it_consumable_request_line
from . import bp_it_consumable_res_partner
from . import bp_it_consumable_hr_employee
from . import bp_it_consumable_equipment
